const accountId = 1331010411981
let accountEmail = "Debanjan@gmail.com"
var accountPassword = "123560"
accountCity = "Kolkata"

// accountId = we cannot change the const keyword after declaration

console.log(accountId)

accountEmail = "Apna@gmail.com"
accountpassword = "4523"
accountCity = "jaypur"

// accountState; undefine. 

// console.log(accountEmail)
// console.log(accountPassword)
// console.log(accountCity)
// we can use console table.

console.log([accountId, accountEmail,  accountPassword, accountCity])

// we can declare the variable using two type 1.let 2.var
// but basically we didnot use the var .because the scope(block)and functional scope problem.
// beacuse var data are easily override.

